### ISSUE TITLE
Release 1.1.0 tidy up code and configure dependencies

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-graphql#1]
1.
```
    implementation 'io.jmix.graphql:jmix-graphql-starter'
    implementation 'com.graphql-java-kickstart:graphql-java-servlet:9.1.0'
    runtimeOnly 'com.graphql-java-kickstart:graphiql-spring-boot-starter:8.1.1'
```

Ideally it should be
```
    implementation 'io.jmix.graphql:jmix-graphql-starter'
```
2.
Rename FooGraphqlBar → FooGraphQLBar

3.
Add package-info.java with @Experimental

**Comment by vadimbasko** [comment]
`runtimeOnly 'com.graphql-java-kickstart:graphiql-spring-boot-starter:8.1.1'`

@web-devel I think we should not include `graphiql` by default in our module. It's up to the user. And there is description in docs how to add it.
