### ISSUE TITLE
Customize filter types for scalar conditions

### ISSUE THREAD

**Issue by vadimbasko** [Haulmont/jmix-graphql#10]
At this moment all scalar filter condition types has same set of operators

`LT, LTE, EQ, NEQ, GT, GTE`

We need different set of operators for each type. For example for boolean is enough `EQ, NEQ`, but for String or Date we need additional as `LIKE` or `BETWEEN`.

Also need to add operators working with `null` values, `ignore case` operators and other cases from `jmix-rest`. 

Full information about available group filter conditions is described in [README.md](https://github.com/Haulmont/jmix-graphql/#filter-conditions)

**Comment by DeNZoL63** [comment]
Date filter conditions will be add in [#31](https://github.com/Haulmont/jmix-graphql/issues/31)

**Comment by DeNZoL63** [comment]
Full information about available group filter conditions is described in [README.md](https://github.com/Haulmont/jmix-graphql/blob/master/README.md)
