### ISSUE TITLE
Validation error of type UnknownType for entity list in frontend screen

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-graphql#100]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2876-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)

**Test Case**
- open project [myFront.zip](https://github.com/Haulmont/jmix-graphql/files/6494651/myFront.zip)
 or create new:
    - add frontend module
    - add graphql addon
    - create entity management frontend component 
- run the app and front
- open browser screen in frontend module:

ER: show list of entities

AR: the data is not shown
![image](https://user-images.githubusercontent.com/73226373/118508399-392d6b80-b740-11eb-96e2-51dd471f6669.png)

GraphQL query:
```
query BookList(
  $limit: Int, 
  $offset: Int, 
  $orderBy: inp_BookOrderBy, 
  $filter: [inp_BookFilterCondition]) {
    BookCount
    BookList(limit: $limit, 
      offset: $offset, 
      orderBy: $orderBy, 
      filter: $filter) {
      id
      title
      year
    }
  }
```

Respond:

```
{
  "errors": [
    {
      "message": "Validation error of type UnknownType: Unknown type inp_BookOrderBy",
      "locations": [
        {
          "line": 4,
          "column": 13
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    },
    {
      "message": "Validation error of type UnknownType: Unknown type inp_BookFilterCondition",
      "locations": [
        {
          "line": 5,
          "column": 13
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
  "data": null
}
```

**Comment by vyacheslav-pushkin** [comment]
After a discussion with @web-devel and @vadimbasko we decided to make the naming more consistent by using capitalized entity name in input names.
