### ISSUE TITLE
DataFetchingException after saving entity with LocalDateDime

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-graphql#135]
**Enviroment**:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3036-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)
JDK 8/11

**TC**:
1. Open attached project -> run app -> run React frontend
2. Open browser -> Open Time Entity Master detail screen
3. Create new entity, fill all fields -> save

**AR**:
![image](https://user-images.githubusercontent.com/45730069/122014970-be07b580-cdd0-11eb-895d-ad1430783bbc.png)
response of graphql query:
```
 {"errors":[{"message":"Exception while fetching data (/upsert_j_TimeEntity) : Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module \"com.fasterxml.jackson.datatype:jackson-datatype-jsr310\" to enable handling (through reference chain: java.util.LinkedH

ashMap[\"localDateTimeField\"])","locations":[{"line":2,"column":3}],"path":["upsert_j_TimeEntity"],"extensions":{"classification":"DataFetchingException"}}],"data":{"upsert_j_TimeEntity":null}}
```

[project link](https://github.com/Haulmont/jmix-graphql/files/6653839/jmfr363.zip)

**Comment by vadimbasko** [comment]
OffsetDateTime issue will be fixed in jmix-framework/jmix#488
