### ISSUE TITLE
Schema downloading error - failed to fetch

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-graphql#149]
**Environment:**
platform version: 1.0.0-SNAPSHOT

**Steps:**
1. Add dependencies
```
implementation 'io.jmix.graphql:jmix-graphql-starter'
runtimeOnly 'com.graphql-java-kickstart:graphiql-spring-boot-starter:8.1.1'
```
2. Add properties
```
jmix.security.oauth2.devMode=true
jmix.security.oauth2.devUsername=admin
graphiql.props.variables.headerEditorEnabled=true
```
3. Run application
4. Execute commands 
```
npm install -g graphqurl
gq http://localhost:8080/graphql --introspect > schema.graphql
```
**AR:**
Executing query... error
Error:  { errors: [ { message: 'failed to fetch' } ] }

schema.graphql is empty

**ER:** 
schema was downloaded successfully

**Comment by vadimbasko** [comment]
Schema could be downloaded via 'Js GraphQL' IDEA Plugin
