### ISSUE TITLE
Support a set of conditions in orderBy argument

### ISSUE THREAD

**Issue by vadimbasko** [Haulmont/jmix-graphql#157]
Example of query with set of conditions:
```graphql
{
 scr_CarList(orderBy: [{manufacturer: ASC}, {garage: {name: ASC}}]) {
  manufacturer
  garage {
    name
  }
}
}
```

Note, that sorting by multiple properties in different directions is not supported

**Comment by web-devel** [comment]
@andreysubbotin  @vadimbasko I suggest to remove this change from 1.1 because it's a breaking change and causes a lot of trouble in studio and client side

**Comment by vadimbasko** [comment]
After discussing with @gorbunkov we decide to remove this feature from 1.1.0

**Comment by zaharchenko-evgeny** [comment]
fixed in https://github.com/Haulmont/jmix-graphql/pull/202
