### ISSUE TITLE
Support a set of conditions in orderBy argument (1.1.x)

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [Haulmont/jmix-graphql#205]
Original ticket https://github.com/Haulmont/jmix-graphql/issues/157

Example of a query with a set of conditions:
```graphql
{
 scr_CarList(orderBy: [{manufacturer: ASC}, {garage: {name: ASC}}]) {
  manufacturer
  garage {
    name
  }
}
}
```

Note, that sorting by multiple properties in different directions is not supported

**Comment by web-devel** [comment]
@zaharchenko-evgeny 
FYI It's a breaking change for clients https://github.com/Haulmont/jmix-graphql/issues/157#issuecomment-925876217
