### ISSUE TITLE
Date filter conditions

### ISSUE THREAD

**Issue by vadimbasko** [Haulmont/jmix-graphql#31]
Make filter conditions `_gt, _gte, _lt, _lte, _eq, _neq, _isNull, _in, _notIn` are working with Date and LocalDateTime scalars.
Full information about available group filter conditions is described in [README.md](https://github.com/Haulmont/jmix-graphql/blob/master/README.md)

**Comment by web-devel** [comment]
Please add description

**Comment by vadimbasko** [comment]
Fixed as part of #10.
