### ISSUE TITLE
The AND, OR operators are not applied to filter

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-graphql#57]
Example of query for operator OR:
```
{scr_CarList(filter: {
    price:{_isNull:true}, 
    OR: {price:{_lte:"20"}}
  })
  {
    _instanceName
    price
  }}
```
 Example of query for operator AND:
```
 {scr_CarList(filter: {
    price:{_gt:"5"}, 
    AND: {price:{_lte:"20"}}
  })
  {
    _instanceName
    price
  }}
```

**ER:** 
- if used OR operator: all instances that match condition 1 OR condition 2 are displayed as a result
- if used AND operator: all instances that match condition 1 AND condition 2 are displayed as a result

**AR:**
Instances that match condition 1 are displayed, condition 2 was ignored

**Comment by vadimbasko** [comment]
Description of using condition compostion added in [README](https://github.com/Haulmont/jmix-graphql#condition-composition).

According to docs query should be
```
{scr_CarList(filter: {
     OR: [
      {price:{_isNull:true}},
      {price:{_lte:"20"}}
    ]
 
  })
  {
    _instanceName
    price
  }
}
```

```
{scr_CarList(filter: {
     AND: [
      {price:{_gt:"5"}},
      {price:{_lte:"20"}}
    ]
 
  })
  {
    _instanceName
    price
  }
}
```
