### ISSUE TITLE
Date and time fields processed incorrectly

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-graphql#60]
**Environment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2751-202
IntelliJ version: IntelliJ IDEA 2020.3.3 (Community Edition)

### Description of the bug:
1. Create new project and add graphQL component
2. Create entity Order with fields with the next types: Date, DateTime, Time, LocalDate, LocalDateTime, LocalTime, OffsetDateTime, OffsetTime
3. Run application and create instance of Order with all attributes
4. Request List of Orders with all attributes by graphQL

Example:
![image](https://user-images.githubusercontent.com/69783839/114879162-feb77280-9e11-11eb-902f-96dee977e696.png)
**ER:**
All fields displayed according to the type
**AR:**
Date field have DateTime format with random Time
In DateTime field Time is incorrect (hours)
Time field have DateTime format and time is incorrect (hours)
Offset dateTime and time fields have a Time zone? and they different (+04:00 & + 05:00)

Responce for example:
```
{  "data": {
    "Order_List": [
      {
        "dateF": "2020-12-11T20:00:00Z",
        "dateTimeF": "2011-11-11T08:31:00Z",
        "timeF": "1969-12-31T23:57:00Z",
        "localDateF": "1980-01-05",
        "localDateTimeF": "2003-03-13T03:01:00",
        "localTimeF": "22:10",
        "offsetTimeF": "11:07+04:00",
        "offsetDateTimeF": "2005-05-21T18:20+05:00"
      }    ]  }}
```

**Comment by DeNZoL63** [comment]
The bug has has fixed in [#66](https://app.zenhub.com/workspaces/jmix-frontend-5fe0992a4308f20011f1c913/issues/haulmont/jmix-graphql/66)
