### ISSUE TITLE
Possible to view an associated entity without permission

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-graphql#64]
**Environment:**
Jmix version: 1.0.0-SNAPSHOT

**Preconditions:**
1. Create new project and add graphQL component
2. Create entity Order
3. Create entity customer and add association attribute with Order
4. Create CRUD screen for created entities

### Description of the bug
1. Create role with permissions for Customer (without permissions for Order)
2. Run application and create instance of Order and Customer
3. Assigne created role to new user
4. get access token for new user and execute query, example:
```
{  CustomerList{
    firstName
    lastName
    order{
      name
      quantity
    }  }}
```

**ER:** order attributes are NOT displayed
**AR:** order attributes are displayed

**Comment by vadimbasko** [comment]
Can't reproduce on current version. Looks like this was fixed as part of issue with security constraints on attributes.
