### ISSUE TITLE
Entity messages query

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-graphql#82]
Implement built-in query to retrieve entity messages for specified locale (as in REST API)

QA Notes: example of using message queries described in [README](https://github.com/Haulmont/jmix-graphql/blob/master/README.md)

**Comment by DartVerder** [comment]
after changing localized message (e.g., for the attribute) and restart application - localized message (displayed in value field) in query results was not change, displaying previous value of localized message
