### ISSUE TITLE
instanceName is always null

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-graphql#9]
Entity `_instanceName` property should be returned with correct value in queries and mutations.

```
{
  carList {
    id
    instanceName
  }
}

{
  "data": {
    "carList": [
      {
        "id": "717bffbf-e3e9-a761-cf29-e3860eba6a27",
        "instanceName": null
      }
    ]
  }
}
```

**Comment by vadimbasko** [comment]
Also no support for  '__typename'
`java.lang.IllegalArgumentException: Property '__typename' not found in scr$Garage`

**Comment by vadimbasko** [comment]
Now in graphql response we can return only fields, that are exist in java entity. In `jmix` there is no `instanceName` property in java, so we need to implement mechanism to add such properties in response.

**Comment by vadimbasko** [comment]
Fixed as part of #26. Issue with nested `_instanceName` exception moved to separate #30.

**Comment by vadimbasko** [comment]
Btw property renamed with  system prefix `_instanceName`

**Comment by DartVerder** [comment]
_instanceName and __typename properties return correct values in queries and mutations
